import type { TutorialStep } from './TutorialContext';

export const ALL_TUTORIAL_STEPS: TutorialStep[] = [
  // ===== DASHBOARD =====
  {
    id: 'welcome',
    screen: 'dashboard',
    targetId: 'header-shop-name',
    titleUrdu: 'Welcome — IceStock Pro',
    titleEnglish: 'Welcome — IceStock Pro',
    descUrdu: 'Yeh aapka shop dashboard hai. Yahan se aapki saari stock, sales aur purchases ka summary dikhai deta hai.',
    descEnglish: 'This is your shop dashboard. Here you can see the summary of all your stock, sales and purchases.',
    position: 'bottom',
    highlightColor: '#3b82f6',
  },
  {
    id: 'low-stock',
    screen: 'dashboard',
    targetId: 'header-bell',
    titleUrdu: 'Low Stock Alerts',
    titleEnglish: 'Low Stock Alerts',
    descUrdu: 'Bell icon par click karke aap dekh sakte hain kaunsa item kam ho raha hai. Jab stock threshold se neeche aata hai toh yahan notification aata hai.',
    descEnglish: 'Click the bell icon to see which items are running low. When stock goes below the threshold, you get a notification here.',
    position: 'bottom',
    highlightColor: '#f59e0b',
  },
  {
    id: 'target-ring',
    screen: 'dashboard',
    targetId: 'dashboard-target',
    titleUrdu: 'Daily Target Ring',
    titleEnglish: 'Daily Target Ring',
    descUrdu: 'Yeh ring dikhati hai aaj ka target kitna complete hua hai. Settings mein jaake daily target set kar sakte hain.',
    descEnglish: 'This ring shows how much of today\'s target is complete. You can set daily target in Settings.',
    position: 'bottom',
    highlightColor: '#10b981',
  },
  {
    id: 'week-chart',
    screen: 'dashboard',
    targetId: 'dashboard-week-chart',
    titleUrdu: 'Weekly Sales Chart',
    titleEnglish: 'Weekly Sales Chart',
    descUrdu: 'Is chart mein aap pichle 7 din ki sales dekh sakte hain. Kaunsa din best tha aur kaunsa kam — sab pata chalega.',
    descEnglish: 'This chart shows your last 7 days of sales. See which day was best and which was lowest.',
    position: 'top',
    highlightColor: '#8b5cf6',
  },
  {
    id: 'top-items',
    screen: 'dashboard',
    targetId: 'dashboard-top-items',
    titleUrdu: 'Top Selling Items',
    titleEnglish: 'Top Selling Items',
    descUrdu: 'Sabse zyada bikne wale items yahan dikhte hain. Yeh aapko batata hai kaunsa product sabse popular hai.',
    descEnglish: 'Best-selling items appear here. This tells you which product is most popular.',
    position: 'top',
    highlightColor: '#ec4899',
  },

  // ===== STOCK =====
  {
    id: 'stock-tab',
    screen: 'stock',
    targetId: 'nav-stock',
    titleUrdu: 'Stock Management',
    titleEnglish: 'Stock Management',
    descUrdu: 'Stock tab par click karein. Yahan se aap apne saari items ka stock add, edit aur manage kar sakte hain.',
    descEnglish: 'Click the Stock tab. Here you can add, edit and manage all your items\' stock.',
    position: 'top',
    highlightColor: '#3b82f6',
  },
  {
    id: 'add-item',
    screen: 'stock',
    targetId: 'stock-add-button',
    titleUrdu: 'Naya Item Add Karein',
    titleEnglish: 'Add New Item',
    descUrdu: 'Plus button par click karke naya item add karein. Naam, variant, price aur stock quantity daalein.',
    descEnglish: 'Click the plus button to add a new item. Enter name, variant, price and stock quantity.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'item-card',
    screen: 'stock',
    targetId: 'stock-item-card',
    titleUrdu: 'Item Card — Edit ya Delete',
    titleEnglish: 'Item Card — Edit or Delete',
    descUrdu: 'Har item ka card dikhai deta hai. Is par click karke edit karein ya swipe karke delete karein. Stock adjust bhi kar sakte hain.',
    descEnglish: 'Each item card is shown here. Click to edit, swipe to delete. You can also adjust stock.',
    position: 'left',
    highlightColor: '#f59e0b',
  },
  {
    id: 'category-filter',
    screen: 'stock',
    targetId: 'stock-category-filter',
    titleUrdu: 'Category Se Filter Karein',
    titleEnglish: 'Filter by Category',
    descUrdu: 'Category buttons se items ko filter kar sakte hain. Sirf cups, sirf cones ya saare items — jo dekhna ho select karein.',
    descEnglish: 'Filter items by category buttons. View only cups, cones, or all items — select what you want to see.',
    position: 'bottom',
    highlightColor: '#8b5cf6',
  },

  // ===== SALES =====
  {
    id: 'sales-tab',
    screen: 'sales',
    targetId: 'nav-sales',
    titleUrdu: 'Sales Section',
    titleEnglish: 'Sales Section',
    descUrdu: 'Sales tab par jaake aap apni saari sales record kar sakte hain. Invoice generate karein aur WhatsApp par bhejein.',
    descEnglish: 'Go to the Sales tab to record all your sales. Generate invoices and send them via WhatsApp.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'cart-add',
    screen: 'sales',
    targetId: 'sales-cart-add',
    titleUrdu: 'Cart Mein Item Add Karein',
    titleEnglish: 'Add Item to Cart',
    descUrdu: 'Item select karein aur quantity daalein. Add to Cart par click karein. Multiple items add kar sakte hain.',
    descEnglish: 'Select an item and enter quantity. Click Add to Cart. You can add multiple items.',
    position: 'top',
    highlightColor: '#3b82f6',
  },
  {
    id: 'machine-type',
    screen: 'sales',
    targetId: 'sales-machine-type',
    titleUrdu: 'Machine Type Select Karein',
    titleEnglish: 'Select Machine Type',
    descUrdu: 'Ice cream ya juice — kaunsi machine se sale ho rahi hai select karein. Yeh reports mein kaam aata hai.',
    descEnglish: 'Select whether the sale is from ice cream or juice machine. This helps in reports.',
    position: 'bottom',
    highlightColor: '#f59e0b',
  },
  {
    id: 'checkout',
    screen: 'sales',
    targetId: 'sales-checkout',
    titleUrdu: 'Checkout — Payment Karein',
    titleEnglish: 'Checkout — Make Payment',
    descUrdu: 'Jab saare items cart mein ho, Checkout par click karein. Cash ya credit — jo bhi mode ho select karein aur complete karein.',
    descEnglish: 'When all items are in cart, click Checkout. Select payment mode — cash or credit — and complete the sale.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'whatsapp-share',
    screen: 'sales',
    targetId: 'sales-whatsapp',
    titleUrdu: 'WhatsApp Par Invoice Bhejein',
    titleEnglish: 'Send Invoice via WhatsApp',
    descUrdu: 'Sale complete hone ke baad WhatsApp button par click karein. Invoice automatically WhatsApp par bhej diya jayega.',
    descEnglish: 'After sale is complete, click the WhatsApp button. The invoice will be automatically sent via WhatsApp.',
    position: 'left',
    highlightColor: '#22c55e',
  },
  {
    id: 'credit-sale',
    screen: 'sales',
    targetId: 'sales-credit',
    titleUrdu: 'Credit (Udhaar) Sale',
    titleEnglish: 'Credit (Udhaar) Sale',
    descUrdu: 'Agar customer ko udhaar dena hai, toh Credit select karein aur customer ka naam daalein. Udhaar ledger mein record ho jayega.',
    descEnglish: 'If giving credit to customer, select Credit and enter customer name. It will be recorded in the Udhaar ledger.',
    position: 'top',
    highlightColor: '#f59e0b',
  },

  // ===== PURCHASE =====
  {
    id: 'purchase-tab',
    screen: 'purchase',
    targetId: 'nav-purchase',
    titleUrdu: 'Purchase Section',
    titleEnglish: 'Purchase Section',
    descUrdu: 'Yahan se aap apni saari purchases record kar sakte hain — cones, cups, syrup ya koi bhi cheez.',
    descEnglish: 'Record all your purchases here — cones, cups, syrup or anything else.',
    position: 'top',
    highlightColor: '#8b5cf6',
  },
  {
    id: 'add-purchase',
    screen: 'purchase',
    targetId: 'purchase-add-button',
    titleUrdu: 'Naya Purchase Add Karein',
    titleEnglish: 'Add New Purchase',
    descUrdu: 'Plus button se naya purchase add karein. Item select karein, quantity aur rate daalein. Supplier bhi choose kar sakte hain.',
    descEnglish: 'Add new purchase with the plus button. Select item, enter quantity and rate. You can also choose a supplier.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'purchase-history',
    screen: 'purchase',
    targetId: 'purchase-history',
    titleUrdu: 'Purchase History',
    titleEnglish: 'Purchase History',
    descUrdu: 'Saari purchases ki list yahan dikhai deti hai. Date, item, quantity aur total — sab kuch dekh sakte hain.',
    descEnglish: 'All purchase records appear here. See date, item, quantity and total — everything at a glance.',
    position: 'top',
    highlightColor: '#3b82f6',
  },

  // ===== REPORTS =====
  {
    id: 'reports-tab',
    screen: 'reports',
    targetId: 'nav-reports',
    titleUrdu: 'Reports Section',
    titleEnglish: 'Reports Section',
    descUrdu: 'Yahan se aap apne poore business ka report dekh sakte hain — sales, purchases, profit aur loss.',
    descEnglish: 'View your entire business report here — sales, purchases, profit and loss.',
    position: 'top',
    highlightColor: '#ec4899',
  },
  {
    id: 'date-range',
    screen: 'reports',
    targetId: 'reports-date-range',
    titleUrdu: 'Date Range Select Karein',
    titleEnglish: 'Select Date Range',
    descUrdu: 'Aaj, 7 din, 30 din ya custom range — jo period ka report chahiye wo select karein.',
    descEnglish: 'Select today, 7 days, 30 days or custom range — choose the period you want to see.',
    position: 'bottom',
    highlightColor: '#f59e0b',
  },
  {
    id: 'export-pdf',
    screen: 'reports',
    targetId: 'reports-export',
    titleUrdu: 'PDF Export Karein',
    titleEnglish: 'Export as PDF',
    descUrdu: 'Report ko PDF mein export kar sakte hain. Print karne ya share karne ke liye bahut useful hai.',
    descEnglish: 'Export the report as PDF. Very useful for printing or sharing.',
    position: 'top',
    highlightColor: '#ef4444',
  },

  // ===== SETTINGS =====
  {
    id: 'settings-tab',
    screen: 'settings',
    targetId: 'header-settings',
    titleUrdu: 'Settings Section',
    titleEnglish: 'Settings Section',
    descUrdu: 'Gear icon par click karke settings kholein. Yahan se aap apni shop ka naam, theme, aur bahut kuch customize kar sakte hain.',
    descEnglish: 'Click the gear icon to open Settings. Customize your shop name, theme and much more.',
    position: 'bottom',
    highlightColor: '#6b7280',
  },
  {
    id: 'shop-name',
    screen: 'settings',
    targetId: 'settings-shop-name',
    titleUrdu: 'Shop Ka Naam Change Karein',
    titleEnglish: 'Change Shop Name',
    descUrdu: 'Apne shop ka naam daalein jo header mein dikhai dega. Invoices par bhi yahi naam aayega.',
    descEnglish: 'Enter your shop name that appears in the header. This name will also appear on invoices.',
    position: 'bottom',
    highlightColor: '#3b82f6',
  },
  {
    id: 'pin-lock',
    screen: 'settings',
    targetId: 'settings-pin',
    titleUrdu: 'PIN Lock Lagayein',
    titleEnglish: 'Set PIN Lock',
    descUrdu: '4-digit PIN set karein taake sirf aap hi app kholein. Har baar open par PIN mangega.',
    descEnglish: 'Set a 4-digit PIN so only you can open the app. It will ask for PIN every time you open.',
    position: 'bottom',
    highlightColor: '#f59e0b',
  },
  {
    id: 'categories',
    screen: 'settings',
    targetId: 'settings-categories',
    titleUrdu: 'Categories Manage Karein',
    titleEnglish: 'Manage Categories',
    descUrdu: 'Nayi categories add karein ya purani edit/delete karein. Items ko categories mein organize karein.',
    descEnglish: 'Add new categories or edit/delete old ones. Organize your items into categories.',
    position: 'bottom',
    highlightColor: '#8b5cf6',
  },
  {
    id: 'backup',
    screen: 'settings',
    targetId: 'settings-backup',
    titleUrdu: 'Backup Download Karein',
    titleEnglish: 'Download Backup',
    descUrdu: 'Apne saare data ka backup download karein. Agar phone badle toh yahan se restore kar sakte hain.',
    descEnglish: 'Download backup of all your data. If you change phones, you can restore from here.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'customers',
    screen: 'settings',
    targetId: 'settings-customers',
    titleUrdu: 'Customers (Udhaar) Manager',
    titleEnglish: 'Customers (Udhaar) Manager',
    descUrdu: 'Saare udhaar customers ki list dekhein. Har customer ka ledger check karein aur payment receive karein.',
    descEnglish: 'View all credit customers list. Check each customer\'s ledger and receive payments.',
    position: 'bottom',
    highlightColor: '#f59e0b',
  },
  {
    id: 'expenses',
    screen: 'settings',
    targetId: 'settings-expenses',
    titleUrdu: 'Expenses Track Karein',
    titleEnglish: 'Track Expenses',
    descUrdu: 'Roz ke kharche jaise bijli, rent, salary yahan record karein. Profit calculation mein help karta hai.',
    descEnglish: 'Record daily expenses like electricity, rent, salary here. Helps in profit calculation.',
    position: 'bottom',
    highlightColor: '#ef4444',
  },
  {
    id: 'wastage',
    screen: 'settings',
    targetId: 'settings-wastage',
    titleUrdu: 'Wastage Record Karein',
    titleEnglish: 'Record Wastage',
    descUrdu: 'Jo items kharab ho gaye ya expire ho gaye unki wastage record karein. Stock accurate rahega.',
    descEnglish: 'Record items that got spoiled or expired as wastage. Keeps your stock accurate.',
    position: 'bottom',
    highlightColor: '#f97316',
  },
  {
    id: 'suppliers',
    screen: 'settings',
    targetId: 'settings-suppliers',
    titleUrdu: 'Suppliers Manager',
    titleEnglish: 'Suppliers Manager',
    descUrdu: 'Apne saare suppliers ki list maintain karein. Contact info aur purchase history dekhein.',
    descEnglish: 'Maintain a list of all your suppliers. See contact info and purchase history.',
    position: 'bottom',
    highlightColor: '#3b82f6',
  },
  {
    id: 'theme',
    screen: 'settings',
    targetId: 'settings-theme',
    titleUrdu: 'Theme Change Karein',
    titleEnglish: 'Change Theme',
    descUrdu: 'Light ya Dark mode select karein. Apni pasand ka theme choose karein.',
    descEnglish: 'Select Light or Dark mode. Choose the theme you prefer.',
    position: 'bottom',
    highlightColor: '#6b7280',
  },
  {
    id: 'daily-target',
    screen: 'settings',
    targetId: 'settings-target',
    titleUrdu: 'Daily Target Set Karein',
    titleEnglish: 'Set Daily Target',
    descUrdu: 'Apna roz ka sales target set karein. Dashboard ring se progress dekhein.',
    descEnglish: 'Set your daily sales target. See progress from the dashboard ring.',
    position: 'bottom',
    highlightColor: '#10b981',
  },
  {
    id: 'urdu-toggle',
    screen: 'settings',
    targetId: 'settings-language',
    titleUrdu: 'Language Toggle',
    titleEnglish: 'Language Toggle',
    descUrdu: 'English ya Urdu — jo bhi zyada samajh aaye wo select karein.',
    descEnglish: 'Select English or Urdu — whichever you understand better.',
    position: 'bottom',
    highlightColor: '#8b5cf6',
  },

  // ===== PAYMENT (when not paid) =====
  {
    id: 'payment-activate',
    screen: 'payment',
    targetId: 'payment-activate-button',
    titleUrdu: 'Payment — Activate Karein',
    titleEnglish: 'Payment — Activate Now',
    descUrdu: 'App istemal karne ke liye payment karein. Activate Now par click karein aur package select karein.',
    descEnglish: 'To use the app, make a payment. Click Activate Now and select a package.',
    position: 'top',
    highlightColor: '#3b82f6',
  },
  {
    id: 'payment-package',
    screen: 'payment',
    targetId: 'payment-package-list',
    titleUrdu: 'Package Select Karein',
    titleEnglish: 'Select a Package',
    descUrdu: '10 packages mein se apna pasand ka chunein. Original package real price hai, baaki mein discount hai.',
    descEnglish: 'Choose from 10 packages. Original package is the real price, others have discounts.',
    position: 'top',
    highlightColor: '#10b981',
  },
  {
    id: 'payment-method',
    screen: 'payment',
    targetId: 'payment-method',
    titleUrdu: 'Payment Method Chunein',
    titleEnglish: 'Choose Payment Method',
    descUrdu: 'Full pay karein ya installment plan chunein. Daily, weekly ya monthly — jo方便 ho.',
    descEnglish: 'Pay in full or choose installment plan. Daily, weekly or monthly — whichever is convenient.',
    position: 'top',
    highlightColor: '#f59e0b',
  },
  {
    id: 'payment-proof',
    screen: 'payment',
    targetId: 'payment-form',
    titleUrdu: 'Payment Proof Bhejein',
    titleEnglish: 'Submit Payment Proof',
    descUrdu: 'Transaction ID aur phone number daalein. Submit par click karein. Admin approve karega toh saari features unlock ho jayengi.',
    descEnglish: 'Enter transaction ID and phone number. Click Submit. Once admin approves, all features will unlock.',
    position: 'top',
    highlightColor: '#8b5cf6',
  },
];
